version: '3.8'

services:
  # load balancer
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - collector

  collector:
    build: .
    deploy:
      replicas: 3
    volumes:
      - collector_data:/root/

volumes:
  collector_data: